In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/clean/cleaned_dataset.csv")

df.head()

,StudyHours,Attendance,Resources,Extracurricular,Motivation,Internet,Gender,Age,LearningStyle,OnlineCourses,Discussions,AssignmentCompletion,ExamScore,EduTech,StressLevel,FinalGrade
0,19,64,1,0,0,1,0,19,2,8,1,59,40,0,1,3
1,19,64,1,0,0,1,0,23,3,16,0,90,66,0,1,2
2,19,64,1,0,0,1,0,28,1,19,0,67,99,1,1,0
3,19,64,1,1,0,1,0,19,2,8,1,59,40,0,1,3
4,19,64,1,1,0,1,0,23,3,16,0,90,66,0,1,2

In [4]:
X = df.drop(columns=["FinalGrade", "ExamScore"])
y = df["FinalGrade"]

In [5]:
print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFeatures:")
print(X.columns.tolist())

print("\nTarget classes:")
print(sorted(y.unique()))

X shape: (12469, 14)
y shape: (12469,)

Features:
['StudyHours', 'Attendance', 'Resources', 'Extracurricular', 'Motivation', 'Internet', 'Gender', 'Age', 'LearningStyle', 'OnlineCourses', 'Discussions', 'AssignmentCompletion', 'EduTech', 'StressLevel']

Target classes:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3)]

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [7]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (9975, 14)
X_test : (2494, 14)
y_train: (9975,)
y_test : (2494,)

In [8]:
numerical_features = [
    "StudyHours",
    "Attendance",
    "Age",
    "OnlineCourses",
    "AssignmentCompletion"
]

categorical_features = [
    "Resources",
    "Extracurricular",
    "Motivation",
    "Internet",
    "Gender",
    "LearningStyle",
    "Discussions",
    "EduTech",
    "StressLevel"
]

In [9]:
print("Numerical features:", numerical_features)
print("Number of numerical features:", len(numerical_features))

print("\nCategorical features:", categorical_features)
print("Number of categorical features:", len(categorical_features))

Numerical features: ['StudyHours', 'Attendance', 'Age', 'OnlineCourses', 'AssignmentCompletion']
Number of numerical features: 5

Categorical features: ['Resources', 'Extracurricular', 'Motivation', 'Internet', 'Gender', 'LearningStyle', 'Discussions', 'EduTech', 'StressLevel']
Number of categorical features: 9

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [11]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [12]:
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [13]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_pipeline, numerical_features),
        ("cat", categorical_pipeline, categorical_features)
    ]
)

In [14]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [15]:
print("Original X_train shape:", X_train.shape)
print("Processed X_train shape:", X_train_processed.shape)

print("\nOriginal X_test shape:", X_test.shape)
print("Processed X_test shape:", X_test_processed.shape)

Original X_train shape: (9975, 14)
Processed X_train shape: (9975, 28)

Original X_test shape: (2494, 14)
Processed X_test shape: (2494, 28)

In [16]:
feature_names = preprocessor.get_feature_names_out()

print("Number of processed features:", len(feature_names))
print("\nProcessed feature names:")
print(feature_names)

Number of processed features: 28

Processed feature names:
['num__StudyHours' 'num__Attendance' 'num__Age' 'num__OnlineCourses'
 'num__AssignmentCompletion' 'cat__Resources_0' 'cat__Resources_1'
 'cat__Resources_2' 'cat__Extracurricular_0' 'cat__Extracurricular_1'
 'cat__Motivation_0' 'cat__Motivation_1' 'cat__Motivation_2'
 'cat__Internet_0' 'cat__Internet_1' 'cat__Gender_0' 'cat__Gender_1'
 'cat__LearningStyle_0' 'cat__LearningStyle_1' 'cat__LearningStyle_2'
 'cat__LearningStyle_3' 'cat__Discussions_0' 'cat__Discussions_1'
 'cat__EduTech_0' 'cat__EduTech_1' 'cat__StressLevel_0'
 'cat__StressLevel_1' 'cat__StressLevel_2']

In [18]:
X_train_processed_df = pd.DataFrame(
    X_train_processed,
    columns=feature_names
)

X_test_processed_df = pd.DataFrame(
    X_test_processed,
    columns=feature_names
)

X_train_processed_df.head()

,num__StudyHours,num__Attendance,num__Age,num__OnlineCourses,num__AssignmentCompletion,cat__Resources_0,cat__Resources_1,cat__Resources_2,cat__Extracurricular_0,cat__Extracurricular_1,...,cat__LearningStyle_1,cat__LearningStyle_2,cat__LearningStyle_3,cat__Discussions_0,cat__Discussions_1,cat__EduTech_0,cat__EduTech_1,cat__StressLevel_0,cat__StressLevel_1,cat__StressLevel_2
0,-0.669569,1.640203,-1.003429,-1.617366,1.463577,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1,-0.339231,-1.059679,-1.574665,1.664680,-1.330551,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
2,-0.339231,-0.014564,-0.717811,-0.140445,0.645784,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,-0.669569,0.420901,0.424662,1.500578,-0.172010,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
4,-0.339231,0.943459,1.281516,-0.632752,0.850232,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [19]:
print("Processed training data shape:", X_train_processed_df.shape)
print("Processed testing data shape:", X_test_processed_df.shape)

Processed training data shape: (9975, 28)
Processed testing data shape: (2494, 28)

In [20]:
train_processed = X_train_processed_df.copy()
train_processed["FinalGrade"] = y_train.values

In [21]:
test_processed = X_test_processed_df.copy()
test_processed["FinalGrade"] = y_test.values

In [22]:
print("Train processed:", train_processed.shape)
print("Test processed :", test_processed.shape)

Train processed: (9975, 29)
Test processed : (2494, 29)

In [23]:
train_processed.to_csv(
    "../data/clean/train_processed.csv",
    index=False
)

test_processed.to_csv(
    "../data/clean/test_processed.csv",
    index=False
)

In [24]:
import joblib

joblib.dump(
    preprocessor,
    "../models/preprocessor.joblib"
)

print("Preprocessor saved successfully.")

Preprocessor saved successfully.